# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImgClassify.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ImgClassify.proto',
  package='gesture_rpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11ImgClassify.proto\x12\x0bgesture_rpc\"f\n\x04imgs\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0f\n\x07num_img\x18\x02 \x01(\x05\x12&\n\x07\x61ll_img\x18\x03 \x03(\x0b\x32\x15.gesture_rpc.imgs.img\x1a\x19\n\x03img\x12\x12\n\nsingle_img\x18\x01 \x03(\x05\".\n\nclassified\x12\x0f\n\x07num_img\x18\x01 \x01(\x05\x12\x0f\n\x07\x63lasses\x18\x02 \x03(\t2U\n\x0f\x43lassifyService\x12\x42\n\x0e\x43lassifyImages\x12\x11.gesture_rpc.imgs\x1a\x17.gesture_rpc.classified\"\x00(\x01\x30\x01\x62\x06proto3')
)




_IMGS_IMG = _descriptor.Descriptor(
  name='img',
  full_name='gesture_rpc.imgs.img',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='single_img', full_name='gesture_rpc.imgs.img.single_img', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=136,
)

_IMGS = _descriptor.Descriptor(
  name='imgs',
  full_name='gesture_rpc.imgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='gesture_rpc.imgs.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_img', full_name='gesture_rpc.imgs.num_img', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='all_img', full_name='gesture_rpc.imgs.all_img', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_IMGS_IMG, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=136,
)


_CLASSIFIED = _descriptor.Descriptor(
  name='classified',
  full_name='gesture_rpc.classified',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_img', full_name='gesture_rpc.classified.num_img', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classes', full_name='gesture_rpc.classified.classes', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=184,
)

_IMGS_IMG.containing_type = _IMGS
_IMGS.fields_by_name['all_img'].message_type = _IMGS_IMG
DESCRIPTOR.message_types_by_name['imgs'] = _IMGS
DESCRIPTOR.message_types_by_name['classified'] = _CLASSIFIED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

imgs = _reflection.GeneratedProtocolMessageType('imgs', (_message.Message,), dict(

  img = _reflection.GeneratedProtocolMessageType('img', (_message.Message,), dict(
    DESCRIPTOR = _IMGS_IMG,
    __module__ = 'ImgClassify_pb2'
    # @@protoc_insertion_point(class_scope:gesture_rpc.imgs.img)
    ))
  ,
  DESCRIPTOR = _IMGS,
  __module__ = 'ImgClassify_pb2'
  # @@protoc_insertion_point(class_scope:gesture_rpc.imgs)
  ))
_sym_db.RegisterMessage(imgs)
_sym_db.RegisterMessage(imgs.img)

classified = _reflection.GeneratedProtocolMessageType('classified', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFIED,
  __module__ = 'ImgClassify_pb2'
  # @@protoc_insertion_point(class_scope:gesture_rpc.classified)
  ))
_sym_db.RegisterMessage(classified)



_CLASSIFYSERVICE = _descriptor.ServiceDescriptor(
  name='ClassifyService',
  full_name='gesture_rpc.ClassifyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=186,
  serialized_end=271,
  methods=[
  _descriptor.MethodDescriptor(
    name='ClassifyImages',
    full_name='gesture_rpc.ClassifyService.ClassifyImages',
    index=0,
    containing_service=None,
    input_type=_IMGS,
    output_type=_CLASSIFIED,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLASSIFYSERVICE)

DESCRIPTOR.services_by_name['ClassifyService'] = _CLASSIFYSERVICE

# @@protoc_insertion_point(module_scope)
